### ISSUE TITLE
类的静态成员变量和静态成员函数各有哪些特性？

### ISSUE THREAD

**Issue by Sogrey** [Sogrey/c-cpp-QA#153]
## 静态成员变量
静态成员变量需要在类内声明（加static），在类外初始化（不能加static），如下例所示；

- 静态成员变量在类外单独分配存储空间，位于全局数据区，因此静态成员变量的生命周期不依赖于类的某个对象，而是所有类的对象共享静态成员变量；
- 可以通过对象名直接访问公有静态成员变量；
- 可以通过类名直接调用公有静态成员变量，即不需要通过对象，这一点是普通成员变量所不具备的。

``` cpp
class example{
public:
static int m_int; //static成员变量
};
 
int example::m_int = 0; //没有static
 
cout<<example::m_int; //可以直接通过类名调用静态成员变量
```

## 静态成员函数

- 静态成员函数是类所共享的；
- 静态成员函数可以访问静态成员变量，但是不能直接访问普通成员变量（需要通过对象来访问）；需要注意的是普通成员函数既可以访问普通成员变量，也可以访问静态成员变量；
- 可以通过对象名直接访问公有静态成员函数；
- 可以通过类名直接调用公有静态成员函数，即不需要通过对象，这一点是普通成员函数所不具备的。

``` cpp
class example{
private:
static int m_int_s; //static成员变量
int m_int;
static int getI() //静态成员函数在普通成员函数前加static即可
{
  return m_int_s; //如果返回m_int则报错，但是可以return d.m_int是合法的
}
};
 
cout<<example::getI(); //可以直接通过类名调用静态成员变量
```

---
- [ ] [static 有什么作用 · Issue #95 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/95)
- [ ] [C 语言的关键字 static 和 C++ 的关键字 static 有什么区别 · Issue #69 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/69)
- [ ] [关键字static的作用是什么? · Issue #44 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/44)
- [ ] [C++中static关键字的作用？ · Issue #4 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/4)
