### ISSUE TITLE
当i是一个整数的时候++i和i++那个更快一点？i++和++i的区别是什么？

### ISSUE THREAD

**Issue by Sogrey** [Sogrey/c-cpp-QA#155]
理论上++i更快，实际与编译器优化有关，通常几乎无差别。
``` cpp
//i++实现代码为：
int operator++(int)
{
    int temp = *this;
    ++*this;
    return temp;
}//返回一个int型的对象本身
 ```
``` cpp
// ++i实现代码为：
int& operator++()
{
    *this += 1;
    return *this;
}//返回一个int型的对象引用
```
i++和++i的考点比较多，简单来说，就是i++返回的是i的值，而++i返回的是i+1的值。也就是++i是一个确定的值，是一个可修改的左值，如下使用：
``` cpp
cout << ++(++(++i)) << endl;
cout << ++ ++i << endl;
```
可以不停的嵌套++i。
这里有很多的经典笔试题，一起来观摩下：
``` cpp
int main()
{
    int i = 1;
    printf("%d,%d\n", ++i, ++i);    //3,3
    printf("%d,%d\n", ++i, i++);    //5,3
    printf("%d,%d\n", i++, i++);    //6,5
    printf("%d,%d\n", i++, ++i);    //8,9
    system("pause");
    return 0;
}
```
首先是函数的参数入栈顺序从右向左入栈的，计算顺序也是从右往左计算的，不过都是计算完以后再进行的压栈操作：

对于第1个printf，首先执行++i，返回值是i，这时i的值是2，再次执行++i，返回值是i，得到i=3，将i压入栈中，此时i为3，也就是压入3，3；

对于第2个printf，首先执行i++，返回值是原来的i，也就是3，再执行++i，返回值是i，依次将3，5压入栈中得到输出结果

对于第3个printf，首先执行i++，返回值是5，再执行i++返回值是6，依次将5，6压入栈中得到输出结果

对于第4个printf，首先执行++i，返回i，此时i为8，再执行i++，返回值是8，此时i为9，依次将i，8也就是9，8压入栈中，得到输出结果。

上面的分析也是基于VS搞的，不过准确来说函数多个参数的计算顺序是未定义的(the order of evaluation of function arguments are undefined)。笔试题目的运行结果随不同的编译器而异。

---
- [ ] [说⼀下++i和i++的区别。 · Issue #7 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/7)
- [ ] [++i和i++的实现？ · Issue #19 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/19)
- [ ] [什么是迭代器失效？++iterator和iterator++哪个效率高？ · Issue #142 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/142)
