### ISSUE TITLE
int a[5]，a和&a是不是一样？

### ISSUE THREAD

**Issue by Sogrey** [Sogrey/c-cpp-QA#161]
一样

> 注意：本题中为数组

----

- [ ] [数组名和指针的区别 · Issue #98 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/98)
- [ ] [简述数组与指针的区别？ · Issue #60 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/60)
- [ ] [a与&a的区别 · Issue #12 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/12)
