### ISSUE TITLE
int a[] = {1,2,3,4,5}; ++a;*a=?

### ISSUE THREAD

**Issue by Sogrey** [Sogrey/c-cpp-QA#163]
2

---

- [ ] [int a[5]，a和&a是不是一样？ · Issue #161 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/161)
- [ ] [数组名和指针的区别 · Issue #98 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/98)
- [ ] [简述数组与指针的区别？ · Issue #60 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/60)
- [ ] [a与&a的区别 · Issue #12 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/12)
