### ISSUE TITLE
malloc、free是做什么的，并举例。

### ISSUE THREAD

**Issue by Sogrey** [Sogrey/c-cpp-QA#166]
`malloc`是用来开辟内存的，`free`是用来释放内存的。

``` cpp
int *a=(int*)malloc(10*sizeof(int));

free(a);
```

----

- [ ] [Ｃ中的 malloc 和Ｃ＋＋中的 new 有什么区别 · Issue #70 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/70)
- [ ] [new、delete、malloc、free关系 · Issue #46 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/46)
- [ ] [C++中有malloc/free，为什么还需要new/delete? · Issue #2 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/2)
