### ISSUE TITLE
vector的底层原理

### ISSUE THREAD

**Issue by Sogrey** [Sogrey/c-cpp-QA#188]
vector底层是一个动态数组，包含三个迭代器，start和finish之间是已经被使用的空间范围，end_of_storage是整块连续空间包括备用空间的尾部。

当空间不够装下数据（vec.push_back(val)）时，会自动申请另一片更大的空间（1.5倍或者2倍），然后把原来的数据拷贝到新的内存空间，接着释放原来的那片空间【vector内存增长机制】。

当释放或者删除（vec.clear()）里面的数据时，其存储空间不释放，仅仅是清空了里面的数据。

因此，对vector的任何操作一旦引起了空间的重新配置，指向原vector的所有迭代器会都失效了。

![](https://image.iamshuaidi.com/picture/70.png)

-----
- [ ] [vector 底层原理及其相关面试题-帅地玩编程](https://www.iamshuaidi.com/2299.html)

-----
- [ ] [简单说说vector · Issue #138 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/138)
- [ ] [vector与deque的区别? · Issue #37 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/37)
- [ ] [vector方法push_back与emplace_back的区别? · Issue #38 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/38)
- [ ] [vector的底层原理 · Issue #188 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/188)
- [ ] [vector中的reserve和resize的区别 · Issue #189 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/189)
- [ ] [vector中的size和capacity的区别 · Issue #190 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/190)
- [ ] [vector的元素类型可以是引用吗？ · Issue #191 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/191)
- [ ] [vector迭代器失效的情况 · Issue #192 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/192)
- [ ] [如何正确释放vector的内存(clear(), swap(), shrink_to_fit()) · Issue #193 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/193)
- [ ] [vector 扩容为什么要以1.5倍或者2倍扩容? · Issue #194 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/194)
- [ ] [vector的常用函数 · Issue #195 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/195)
- [ ] [什么情况下用vector，什么情况下用list，什么情况下用deque · Issue #199 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/199)
- [ ] [Vector如何释放空间? · Issue #201 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/201)
- [ ] [为何map和set不能像vector一样有个reserve函数来预分配数据? · Issue #206 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/206)
- [ ] [vector越界访问下标，map越界访问下标？vector删除元素时会不会释放空间？ · Issue #218 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/218)
- [ ] [频繁对vector调用push_back()对性能的影响和原因？ · Issue #221 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/221)
