### ISSUE TITLE
vector中的reserve和resize的区别

### ISSUE THREAD

**Issue by Sogrey** [Sogrey/c-cpp-QA#189]
- `reserve`是直接扩充到已经确定的大小，可以减少多次开辟、释放空间的问题（优化push_back），就可以提高效率，其次还可以减少多次要拷贝数据的问题。reserve只是保证vector中的空间大小（capacity）最少达到参数所指定的大小n。reserve()只有一个参数。

- `resize()`可以改变有效空间的大小，也有改变默认值的功能。capacity的大小也会随着改变。resize()可以有多个参数。

-----
- [ ] [简单说说vector · Issue #138 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/138)
- [ ] [vector与deque的区别? · Issue #37 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/37)
- [ ] [vector方法push_back与emplace_back的区别? · Issue #38 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/38)
- [ ] [vector的底层原理 · Issue #188 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/188)
- [ ] [vector中的reserve和resize的区别 · Issue #189 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/189)
- [ ] [vector中的size和capacity的区别 · Issue #190 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/190)
- [ ] [vector的元素类型可以是引用吗？ · Issue #191 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/191)
- [ ] [vector迭代器失效的情况 · Issue #192 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/192)
- [ ] [如何正确释放vector的内存(clear(), swap(), shrink_to_fit()) · Issue #193 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/193)
- [ ] [vector 扩容为什么要以1.5倍或者2倍扩容? · Issue #194 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/194)
- [ ] [vector的常用函数 · Issue #195 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/195)
- [ ] [什么情况下用vector，什么情况下用list，什么情况下用deque · Issue #199 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/199)
- [ ] [Vector如何释放空间? · Issue #201 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/201)
- [ ] [为何map和set不能像vector一样有个reserve函数来预分配数据? · Issue #206 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/206)
- [ ] [vector越界访问下标，map越界访问下标？vector删除元素时会不会释放空间？ · Issue #218 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/218)
- [ ] [频繁对vector调用push_back()对性能的影响和原因？ · Issue #221 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/221)

**Comment by Sogrey** [comment]
## vector的reserve()和resize()方法之间有什么区别？


首先，vector的容量capacity()是指在不分配更多内存的情况下可以保存的最多元素个数，而vector的大小size()是指实际包含的元素个数；

其次，vector的reserve(n)方法只改变vector的容量，如果当前容量小于n，则重新分配内存空间，调整容量为n；如果当前容量大于等于n，则无操作；

最后，vector的resize(n)方法改变vector的大小，如果当前容量小于n，则调整容量为n，同时将其全部元素填充为初始值；如果当前容量大于等于n，则不调整容量，只将其前n个元素填充为初始值。
