### ISSUE TITLE
vector迭代器失效的情况

### ISSUE THREAD

**Issue by Sogrey** [Sogrey/c-cpp-QA#192]
当插入一个元素到vector中，由于引起了内存重新分配，所以指向原内存的迭代器全部失效。

当删除容器中一个元素后,该迭代器所指向的元素已经被删除，那么也造成迭代器失效。erase方法会返回下一个有效的迭代器，所以当我们要删除某个元素时，需要it=vec.erase(it);。

---
- [ ] [有指针为什么还要迭代器（STL迭代器的作用）？ · Issue #39 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/39)
- [ ] [简单说说vector · Issue #138 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/138)
- [ ] [vector与deque的区别? · Issue #37 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/37)
- [ ] [vector方法push_back与emplace_back的区别? · Issue #38 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/38)
- [ ] [vector的底层原理 · Issue #188 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/188)
- [ ] [vector中的reserve和resize的区别 · Issue #189 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/189)
- [ ] [vector中的size和capacity的区别 · Issue #190 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/190)
- [ ] [vector的元素类型可以是引用吗？ · Issue #191 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/191)
- [ ] [vector迭代器失效的情况 · Issue #192 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/192)
- [ ] [如何正确释放vector的内存(clear(), swap(), shrink_to_fit()) · Issue #193 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/193)
- [ ] [vector 扩容为什么要以1.5倍或者2倍扩容? · Issue #194 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/194)
- [ ] [vector的常用函数 · Issue #195 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/195)
- [ ] [什么情况下用vector，什么情况下用list，什么情况下用deque · Issue #199 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/199)
- [ ] [Vector如何释放空间? · Issue #201 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/201)
- [ ] [为何map和set不能像vector一样有个reserve函数来预分配数据? · Issue #206 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/206)
- [ ] [vector越界访问下标，map越界访问下标？vector删除元素时会不会释放空间？ · Issue #218 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/218)
- [ ] [频繁对vector调用push_back()对性能的影响和原因？ · Issue #221 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/221)
- [ ] [迭代器失效的问题 · Issue #215 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/215)

**Comment by Sogrey** [comment]
## 为什么vector的插入操作可能会导致迭代器失效？


vector动态增加大小时，并不是在原空间后增加新的空间，而是以原大小的两倍在另外配置一片较大的新空间，然后将内容拷贝过来，并释放原来的空间。由于操作改变了空间，所以迭代器失效。

**Comment by Sogrey** [comment]
## 对于vector可能导致其迭代器失效的操作有哪些

`resize`、`reserve`、`insert`、`assign`、`push_back`等会引起其底层空间改变的操作，都有可能使迭代器失效。
指定位置元素的删除操作--erase
``` cpp
#include <iostream>
using namespace std;
#include <vector>
int main()
{
    int a[] = { 1, 2, 3, 4 };
    vector<int> v(a, a + sizeof(a) / sizeof(int));
    // 使用find查找3所在位置的iterator
    vector<int>::iterator pos = find(v.begin(), v.end(), 3);
    // 删除pos位置的数据，导致pos迭代器失效。
    v.erase(pos);
    cout << *pos << endl; // 此处会导致非法访问
    return 0;
}
```
erase删除pos位置元素后，pos位置之后的元素会往前移动，没有导致底层空间的改变，理论上讲迭代器应该不会失效，但是如果pos刚好是最后一个元素，删完之后pos刚好是end位置，而end位置是没有元素的，那么pos就失效了。所以删除vector中任意位置上元素时，vs就认为该位置迭代器失效了。
