### ISSUE TITLE
vector与deque的区别?

### ISSUE THREAD

**Issue by Sogrey** [Sogrey/c-cpp-QA#37]
1）deque访问容器元素的效率比vector容器慢很多；
 原因在于deque要跨内存块来访问，而vector只是使用一个内存块，不用跨内存的操作。vector容器相当于一个可以动态分配的数组。
2）扩充容器容量的方面deque比vector的效率高很多；
 deque是申请一个小的内存块，然后把新申请的内存块与其它的deque内存块整合起来。
 vector是申请一个比原先更大的新内存块，把原vector里面的数据复制到新的大内存块里面，然后销毁原先的内存块。所以，在容量扩充方面，deque比vector高效，而且内存利用率也高。
3）vector不可以收缩，deque自动收缩；
 vector不支持把容器的容量调小的操作，即容量需求小于实际容量的情况不会有任何操作。而deque因为它是有很多小内存块的组成的，所以有空闲的内存块时，会销毁空闲的内存块，但不会影响deque里面已有的数据。

-----
- [ ] [简单说说vector · Issue #138 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/138)
- [ ] [vector与deque的区别? · Issue #37 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/37)
- [ ] [vector方法push_back与emplace_back的区别? · Issue #38 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/38)
- [ ] [vector的底层原理 · Issue #188 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/188)
- [ ] [vector中的reserve和resize的区别 · Issue #189 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/189)
- [ ] [vector中的size和capacity的区别 · Issue #190 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/190)
- [ ] [vector的元素类型可以是引用吗？ · Issue #191 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/191)
- [ ] [vector迭代器失效的情况 · Issue #192 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/192)
- [ ] [如何正确释放vector的内存(clear(), swap(), shrink_to_fit()) · Issue #193 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/193)
- [ ] [vector 扩容为什么要以1.5倍或者2倍扩容? · Issue #194 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/194)
- [ ] [vector的常用函数 · Issue #195 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/195)
- [ ] [什么情况下用vector，什么情况下用list，什么情况下用deque · Issue #199 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/199)
- [ ] [Vector如何释放空间? · Issue #201 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/201)
- [ ] [为何map和set不能像vector一样有个reserve函数来预分配数据? · Issue #206 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/206)
- [ ] [vector越界访问下标，map越界访问下标？vector删除元素时会不会释放空间？ · Issue #218 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/218)
- [ ] [频繁对vector调用push_back()对性能的影响和原因？ · Issue #221 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/221)
