### ISSUE TITLE
vector方法push_back与emplace_back的区别?

### ISSUE THREAD

**Issue by Sogrey** [Sogrey/c-cpp-QA#38]
push_back()向容器尾部添加元素时，首先会创建这个元素，然后再将这个元素拷贝或者移动到容器中（如果是拷贝的话，事后会自行销毁先前创建的这个元素）；
而emplace_back()在实现时，则是直接在容器尾部创建这个元素，省去了拷贝或移动元素的过程。

-----
- [ ] [简单说说vector · Issue #138 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/138)
- [ ] [vector与deque的区别? · Issue #37 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/37)
- [ ] [vector方法push_back与emplace_back的区别? · Issue #38 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/38)
- [ ] [vector的底层原理 · Issue #188 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/188)
- [ ] [vector中的reserve和resize的区别 · Issue #189 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/189)
- [ ] [vector中的size和capacity的区别 · Issue #190 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/190)
- [ ] [vector的元素类型可以是引用吗？ · Issue #191 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/191)
- [ ] [vector迭代器失效的情况 · Issue #192 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/192)
- [ ] [如何正确释放vector的内存(clear(), swap(), shrink_to_fit()) · Issue #193 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/193)
- [ ] [vector 扩容为什么要以1.5倍或者2倍扩容? · Issue #194 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/194)
- [ ] [vector的常用函数 · Issue #195 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/195)
- [ ] [什么情况下用vector，什么情况下用list，什么情况下用deque · Issue #199 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/199)
- [ ] [Vector如何释放空间? · Issue #201 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/201)
- [ ] [为何map和set不能像vector一样有个reserve函数来预分配数据? · Issue #206 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/206)
- [ ] [vector越界访问下标，map越界访问下标？vector删除元素时会不会释放空间？ · Issue #218 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/218)
- [ ] [频繁对vector调用push_back()对性能的影响和原因？ · Issue #221 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/221)
