### ISSUE TITLE
static 有什么作用

### ISSUE THREAD

**Issue by Sogrey** [Sogrey/c-cpp-QA#95]
static 在 C 中主要用于定义全局静态变量、定义局部静态变量、定义静态函数。

在 C++中新增了两种作用：定义静态数据成员、静态函数成员。

> 注意：因为 static 定义的变量分配在静态区，所以其定义的变量的默认值为 0，普通变量的默认值为随机数，在定义指针变量时要特别注意。

---
- [ ] [C 语言的关键字 static 和 C++ 的关键字 static 有什么区别 · Issue #69 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/69)
- [ ] [关键字static的作用是什么? · Issue #44 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/44)
- [ ] [C++中static关键字的作用？ · Issue #4 · Sogrey/c-cpp-QA](https://github.com/Sogrey/c-cpp-QA/issues/4)

**Comment by Sogrey** [comment]
1.限制变量的作用域(DL:使其只在定义的当前文件中起作用，static是只能由与变量在同一个文件中定义的程序
存取的全局变量。也就是说使全局变量成为文件的私有变量，以致其他文件不可以通过将它们定义为extern而存
取这些变量。)
2.设置变量的存储域（DL：存储在最开始的静态存储空间里面）

**Comment by Sogrey** [comment]
- 静态（局部/全局）变量
- 静态函数
- 类的静态数据成员
- 类的静态成员函数

**Comment by Sogrey** [comment]
在C语言中static用来修饰局部静态变量和外部静态变量和函数，而C++语言还可以用来定义类的成员变量和函数，即静态成员和静态成员函数，C++的静态成员可以在多个对象实例之间进行通信，传递信息。

（1）定义全局静态变量和局部静态变量：在变量前面加上static关键字。初始化的静态变量会在.data段分配内存，未初始化的静态变量会在.bss段分配内存。直到程序结束，静态变量始终会维持前值。只不过全局静态变量和局部静态变量的作用域不一样；

（2）定义静态函数：在函数返回类型前加上static关键字，函数被定义为静态函数。静态函数只能在本源文件中使用；

（3）在变量类型前加上static关键字，变量即被定义为静态变量。静态变量只能在本源文件中使用，比如：
``` cpp
static int a;
static void func();
```
（4）在C++中，static关键字可以用于定义类中的静态成员变量：使用静态数据成员，它既可以被当成全局变量那样去存储，但又被隐藏在类的内部。类中的static静态数据成员拥有一块单独的存储区，而不管创建了多少个该类的对象。所有这些对象的静态数据成员都共享这一块静态存储空间。

（5）在C++中，static关键字可以用于定义类中的静态成员函数：与静态成员变量类似，类里面同样可以定义静态成员函数。只需要在函数前加上关键字static就可以。如静态成员函数也是类的一部分，而不是对象的一部分。所有这些对象的静态数据成员都共享这一块静态存储空间。
